### ISSUE TITLE
Definitive API? 

### ISSUE THREAD

**Issue by fxfactorial** [dtinth/JXA-Cookbook#10]
Is there a way to show just the definitive API? For example, I want to know all the properties or methods of the Application object, where is this?

**Comment by Tatsh** [comment]
`__proto__` ?

**Comment by dtinth** [comment]
First, open the __Script Editor__ application. Then __File__ &rarr; __Open Dictionary__. Choose the app you want. Let's say iTunes, for example.

Select __Language__ to __JavaScript__, and you should see things like this:

<img width="916" alt="screen shot 2015-07-03 at 22 37 10" src="https://cloud.githubusercontent.com/assets/193136/8501899/1ffa92f8-21d4-11e5-8332-7b17565ed862.png">

Please note that this only applies to a specific application. For the Application object, please look at [Commands Reference](https://developer.apple.com/library/mac/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html). It uses the AppleScript syntax, which you must translate into JavaScript syntax by following the guide in the [JXA Release Notes](https://developer.apple.com/library/mac/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/).

By the way, I would really appreciate it if you could update the wiki with the information I posted here, so that others may benefit as well :smile:. I am very busy with other stuff. Thanks!
