### ISSUE TITLE
Semicolons? 

### ISSUE THREAD

**Issue by joedaniels29** [dtinth/JXA-Cookbook#18]
Any particular reason the semicolons were left out of all the code samples? So far as I can tell all Standard JavaScript syntax is require semicolons to delimit a statement, right?

**Comment by Tatsh** [comment]
Perhaps that Apple's own documentation on JXA generally lacks semicolons? 
`;` on nearly every line (especially in example code) is noisy. AppleScript used indents as delimiters and had no end of expression terminators as C-like languages often do.

JavaScript has never required semicolons as it has ['ASI' or automatic semicolon insertion](http://www.ecma-international.org/ecma-262/6.0/#sec-automatic-semicolon-insertion). You only need semicolons to end expressions next to restricted keywords so they can be on the same line (`functionCall(); if (someVar) {}`), and in many cases, a semi-colon can do the same as a `,`especially with`return` due to operator precedence (the last expression will be returned in `return 1 + 2, 2 + 3`).

ASI breaks this code that would otherwise use semicolons on each line ([Whitesmiths style](https://en.wikipedia.org/wiki/Indent_style#Whitesmiths_style)):

```javascript
return
  {
    key: value
  };
```

**Comment by joedaniels29** [comment]
Thanks!
