### ISSUE TITLE
read file as class utf8

### ISSUE THREAD

**Issue by Slavetz** [dtinth/JXA-Cookbook#25]
StandardAdditions of ScriptEditor has a function for reading files and it has the option "as"...

**so i have code in apple script that work nice:**
_read file theFile as «class utf8»_
 
**how can i do this in JS?**
_app.read(Path(theFile), {as: ???});_

**text in my file with utf8:**
AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz
АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя
_-–—,;:!¡?.…·'‚‹›"«()[]§¶@*/\&#%‡•`˜^˙˚°©∂∆+±<=≠>¬|~⁄√∞∫≈≤≥¢$£€ªåÅæçﬁƒºß™Ω

**text in my file without utf8:**
AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz
–Р–∞–С–±–Т–≤–У–≥–Ф–і–Х–µ–Б—С–Ц–ґ–Ч–Ј–Ш–Є–Щ–є–Ъ–Ї–Ы–ї–Ь–Љ–Э–љ–Ю–Њ–Я–њ–†—А–°—Б–Ґ—В–£—Г–§—Д–•—Е–¶—Ж–І—З–®—И–©—Й–™—К–Ђ—Л–ђ—М–≠—Н–Ѓ—О–ѓ—П
_-вАУвАФ,;:!¬°?.вА¶¬Ј'вАЪвАєвАЇ\"¬Ђ()[]¬І¬ґ@*/\\&#%вА°вАҐ`ЋЬ^ЋЩЋЪ¬∞¬©вИВвИЖ+¬±<=вЙ†>¬ђ|~вБДвИЪвИЮвИЂвЙИвЙ§вЙ•¬Ґ$¬£вВђ¬™√•√Е√¶√ІпђБ∆Т¬Ї√ЯвДҐќ©

**Comment by Tatsh** [comment]
This is [unfortunately broken](http://stackoverflow.com/a/31858548/374110). There is no way to specify `«class utf8»` in JXA because the `as` keyword in JXA *only* works with defined types (strings representing classes) that are in the dictionary. Anything that uses ['chevron' syntax](https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptLangGuide/conceptual/ASLR_raw_data.html#//apple_ref/doc/uid/TP40000983-CH225-SW2) like this is not defined. There is also no definition in the dictionary for 'Unicode string' (which is really UTF-16) for JXA.

You will have to use the Objective-C bridge:

```javascript
ObjC.import('Foundation')

const readFile = function (path, encoding) {
    !encoding && (encoding = $.NSUTF8StringEncoding)

    const fm = $.NSFileManager.defaultManager
    const data = fm.contentsAtPath(path)
    const str = $.NSString.alloc.initWithDataEncoding(data, encoding)
    return ObjC.unwrap(str)
}
```

**Comment by JMichaelTX** [comment]
> const str = $.NSString.alloc.initWithDataEncoding(data, encoding)

Thanks for sharing this code snippet.
Where can we find a list of valid "encoding" values?

I have searched, but didn't find a list.

Thanks.

**Comment by Tatsh** [comment]
This is from `NSString.h`. Unfortunately since Swift, [the documentation](https://developer.apple.com/reference/foundation/nsstringencoding?language=objc#declarations) from Apple has suffered a bit. On that page, they only show the `typedef` line and not the actual values. This is likely a bug in their documentation generator. I consider it a major problem.

```c
typedef NSUInteger NSStringEncoding;
NS_ENUM(NSStringEncoding) {
    NSASCIIStringEncoding = 1,		/* 0..127 only */
    NSNEXTSTEPStringEncoding = 2,
    NSJapaneseEUCStringEncoding = 3,
    NSUTF8StringEncoding = 4,
    NSISOLatin1StringEncoding = 5,
    NSSymbolStringEncoding = 6,
    NSNonLossyASCIIStringEncoding = 7,
    NSShiftJISStringEncoding = 8,          /* kCFStringEncodingDOSJapanese */
    NSISOLatin2StringEncoding = 9,
    NSUnicodeStringEncoding = 10,
    NSWindowsCP1251StringEncoding = 11,    /* Cyrillic; same as AdobeStandardCyrillic */
    NSWindowsCP1252StringEncoding = 12,    /* WinLatin1 */
    NSWindowsCP1253StringEncoding = 13,    /* Greek */
    NSWindowsCP1254StringEncoding = 14,    /* Turkish */
    NSWindowsCP1250StringEncoding = 15,    /* WinLatin2 */
    NSISO2022JPStringEncoding = 21,        /* ISO 2022 Japanese encoding for e-mail */
    NSMacOSRomanStringEncoding = 30,

    NSUTF16StringEncoding = NSUnicodeStringEncoding,      /* An alias for NSUnicodeStringEncoding */

    NSUTF16BigEndianStringEncoding = 0x90000100,          /* NSUTF16StringEncoding encoding with explicit endianness specified */
    NSUTF16LittleEndianStringEncoding = 0x94000100,       /* NSUTF16StringEncoding encoding with explicit endianness specified */

    NSUTF32StringEncoding = 0x8c000100,                   
    NSUTF32BigEndianStringEncoding = 0x98000100,          /* NSUTF32StringEncoding encoding with explicit endianness specified */
    NSUTF32LittleEndianStringEncoding = 0x9c000100        /* NSUTF32StringEncoding encoding with explicit endianness specified */
};
```

**Comment by JMichaelTX** [comment]
> This is from NSString.h

Thanks.

**Comment by Tatsh** [comment]
If you are good now please close the issue

**Comment by Slavetz** [comment]
Tatsh, thanks for the answer.
I hope this problem will be solve.
Why Apple did not do something like
app.read(Path(theFile), {as: {class: utf8}});
or
app.read(Path(theFile), {asClass: utf8});
