### ISSUE TITLE
How to work with ObjC functions with pointer parameters?

### ISSUE THREAD

**Issue by sancarn** [dtinth/JXA-Cookbook#27]
Take this as an example:

```
CGError CGGetDisplaysWithRect(CGRect rect, uint32_t maxDisplays, CGDirectDisplayID *displays, uint32_t *matchingDisplayCount);

```

The above function returns a "result code".
However the function is designed to get all the displays which 'contain/intersect' a specified rectangle.

In ObjC this variable, displays, is passed by reference (or by a pointer). i.e.

```
CGGetDisplaysWithRect(rect,<someInt>,&displays,<someInt>)
```

would fill the variable displays with the display IDs for all displays connected to the computer which intersects rectangle rect.

In Javascript however, there are no pointers. Thus I assume there are also no pointers in JXA? How do you deal with these sorts of functions in JXA?

**Comment by Tatsh** [comment]
Unfortunately, this stuff will not translate well to JavaScript. JavaScript uses references for every object and there's a semblance of an idea of primitive types (when you type `a = 1` instead of `a = new Number(1)`), but you cannot pass primitive types by reference in JavaScript.

For this case and almost every case, you have to have a function that will return the correct type of pointer or object reference (opaque reference as heavily used in CoreFoundation code). Also in this case, you also have a problem where you need to pass an array of `CGDirectDisplayID` pointers (to pointers) instead of just one, and you need to pass a pointer to an integer rather than a value. This is where the value to inspect will be stored.

In C code you would do this to call `CGGetDisplaysWithRect()`:

```c
CGDirectDisplayID disp = CGMainDisplayID();
CGDirectDisplayID *displays = (CGDirectDisplayID *)malloc(sizeof(CGDirectDisplayID));
displays[0] = disp;
uint32_t matchingDisplayCount;

CGError err = CGGetDisplaysWithRect(CGRectMake(0, 0, 200, 200), 1, displays, &matchingDisplayCount);

NSLog(@"%u", matchingDisplayCount);
```

(GCC does not require cast on malloc but other compilers are dumb.)

Main thing you need to do with these kind of functions is ensure that, unlike above, no type-qualified pointers get used with the `ObjC.bindFunction()`. Make them take a `void *` type. You also need to use a pre-allocated memory region since you cannot pass a primitive by reference in JavaScript (use `malloc`). That means the value will only be accessible at index 0 of the allocated memory region.

```javascript
ObjC.import('stdlib')
ObjC.import('CoreGraphics')

// arguments: 'name of function', ['return type', [arg1, arg2, ...]]
ObjC.bindFunction('CGGetDisplaysWithRect', ['CGError', ['CGRect', 'uint32_t', 'void *', 'void *']])

const disp = $.CGMainDisplayID()

// Set up the displays array
const displays = $.malloc(4); // sizeof(uint32_t) == sizeof(CGDirectDisplayID) == 4 (on x86, x86-64, arm, arm64)
displays[0] = $.CGMainDisplayID()

// Set up storage point for 'real' return value
const matchingDisplayCountMemory = $.malloc(4)

// First argument
const rect = $.CGRectMake(0, 0, 200, 200)

// Second argument
const maxDisplays = 100

// Call the function
const err = $.CGGetDisplaysWithRect(rect, maxDisplays, displays, matchingDisplayCountMemory)

// Get the actual value, at index 0
const matchingDisplayCount = matchingDisplayCountMemory[0]

// Free the allocated memory, this will not happen automatically!
$.free(displays)
$.free(matchingDisplayCountMemory)

// Inspect the value
console.log(matchingDisplayCount)

// Inspect the error
// https://developer.apple.com/reference/coregraphics/cgerror?language=objc
console.log(err === $.kCGErrorFailure) // and other values

// remove junk new line
$.exit(0)
```

Just FYI, the term is pointer and the act of `&` is `address of`, normally a local variable, but can also mean to resolve the address of a pointer. Using the `*` operator on the value is dereferencing. 

In C, these two lines are equivalent, if you have `int a = 1;`, and `int *b = &a;`:

```c
f(&a);
f(&b);
```

where `f` = `void f(int *v){}` but on the second line, the `&` operator is not necessary.

**Comment by sancarn** [comment]
This is really interesting and a completely different method to how I accomplished the task. Using ObjC.bindFunction() is a really inventive way to get around the problem!

I finally accomplished the task, yesterday, after finding out about the JXA class Ref()

    ObjC.import('Foundation')
    ObjC.import('AppKit')
    var rect = $.CGRectMake(x,y,w,h)
    var displays = Ref()
    $.CGMainDisplayID() //Fully initialise CoreGraphics Framework
    $.CGGetDisplaysWithRect(rect,1,displays,null)
    displayID = displays[0]
    
    //do stuff with displayID
    
    displayID.release

Also something that may interest you, the parameter `maxDisplays` is limited to 32. However you can also get the number of displays from the rectangle at the same time:

    count=Ref()
    $.CGGetDisplaysWithRect(rect,0,null,count)
    maxDisplays = count[0]

**Comment by Tatsh** [comment]
I was unaware you can assign to a call to `Ref()` and pass that. It's good to have multiple ways to do something sometimes.

In your code above, I do not see how these lines do anything, other than pass an 'empty' `Ref()` as the 3rd argument:

```javascript
var displays = Ref()
$.CGMainDisplayID() //Make sure CoreGraphics Framework is fully initialise
$.CGGetDisplaysWithRect(rect,1,displays,null)
```

You would be passing an empty array?

**Comment by sancarn** [comment]
> In your code above, I do not see how these lines do anything...

Well, as far as I am aware, `var displays = Ref()` makes JXA pass a named variable by reference to `$.CGGetDisplaysWithRect(rect,1,displays,null)`. ObjC returns an array to that variable, so that's what JXA receives. you can access the values inside the ref with `displays[0]` in this case.

The important part is $.CGMainDisplayID(). As mentioned in my code:

/*
     * CGMainDisplayID must be called before CGGetDisplaysWithRect.
     * If it isn't the console throws the error:
     *  Assertion failed: (did_initialize), function CGS_REQUIRE_INIT, file Desktop/CGInitialization.c, line 40.
     *  Abort trap: 6
     *
     * Supposedly this is because CGGetDisplaysWithRect, as of OSXYosemite,
     *  no longer initialises CoreGraphics if it isn't already. This is not
     *  normally a problem with GUI applications, however with scripts it is
     *  obviously a problem.
     *
     * Calling CGMainDisplayID() forces CoreGraphics framework to properly initialise
     *  thus the error at CGGetDisplaysWithRect() does not occur.
     *
     * Reference: https://bitbucket.org/ronaldoussoren/pyobjc/issues/132/quartzcgbegindisplayconfiguration-doesnt
     */

**Comment by sancarn** [comment]
Figured actually I should leave the issue open, because otherwise people with the same issue won't see it.

**Comment by Tatsh** [comment]
Ugly magic is what `Ref()` is. It should be far more explicit.

By the way I would prefer you add this information to the Wiki and close this.

**Comment by Tatsh** [comment]
One thing also is that that was your code there and I did not see that just calling the function was to initialise CoreGraphics. I thought it was trying to pass `displays` (a `Ref` object), but it was referencing nothing. `Ref()` makes sense as a replacement for having to calling `malloc` and not having to call `ObjC.bindFunction()`.

It seems the only way to call this function with a defined set of display IDs (second argument, array) is to create a `Ref()` to an array of `uint32_t`, which I haven't seen how to do yet. You still have to create a regular C array (with `malloc`) and redefine the function.

**Comment by sancarn** [comment]
> By the way I would prefer you add this information to the Wiki and close this.

Will do! Thanks for the help btw! 👍

**Comment by JMichaelTX** [comment]
> Figured actually I should leave the issue open, because otherwise people with the same issue won't see it. Then again, perhaps it'd be better going into the cookbook

@sancarn , I agree that it would be good to put this in the cookbook wiki.
I have recently started a section for using ObjC:
[Using Objective C (ObjC) with JXA](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-%28ObjC%29-with-JXA)

Perhaps you could add the relevant parts of the discussion here to that page, or maybe create a new page and link it to the main ObjC page.

I think the discussion here provides tremendous insight into JXA ObjC.

**Comment by sancarn** [comment]
I will try to find time to write something. It's been a long time since I did anything with JXA though. Been focussing more on Windows. However it would be good to have a better reference for Objective C, especially as this side of JXA is, in my opinion, the most important part to know about...

**Comment by sancarn** [comment]
I've spent the last 4 hours performing such an edit. I've added information mostly to the [JXA-ObjC Bridge - The Fundamentals](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-(ObjC)-with-JXA#jxa-objc-bridge---the-fundamentals) section. I cover a the $ object, ObjC object, Ref() function and also some information about syntax conversion.

I'm not sure if the way I have written it is okay or confusing... Will need someone to read through it and make edits where they feel appropriate :)

**Comment by JMichaelTX** [comment]
> I've spent the last 4 hours performing such an edit. I've added information mostly to the JXA-ObjC Bridge - The Fundamentals section.

@sancarn , wow!  This is an awesome contribution.  It really lays out the fundamentals in very clear way.  Thanks so much!.

**Comment by Tatsh** [comment]
Minor nitpick: *Interestingly we can see the ampersand & symbol is next to the variable isDir. In Objective-C (and many other C languages)* -- it should be *and many C-like languages* or simply *and many other languages*.

**Comment by Tatsh** [comment]
Also there's not a consistent spelling of JavaScript. Sometimes it's *javascript* and other times it's *JavaScript*. It should be *JavaScript* throughout.

**Comment by Tatsh** [comment]
In covering the call to `alloc` I think there should be a mention that `()` are not required and seemingly are never required for a method call on the bridge as long as there are zero arguments (call it similar to Ruby if you want). These two lines are equivalent:

```js
$.NSWindow.alloc.initContentRectStyleMaskBackingDefer(...)
$.NSWindow.alloc().initContentRectStyleMaskBackingDefer(...)
```

**Comment by JMichaelTX** [comment]
@Tatsh , thanks for your feedback on @sancarn's wiki update.

Since @sancarn has stated "Will need someone to read through it and make edits where they feel appropriate :)", perhaps the easiest approach to updating the wiki is for each editor to make the changes he/she feels is important, and then post a brief comment in this issue about the changes.
Since it is easy to see and compare revisions to any wiki page, I have found this type of process to work well with other wikis where I have been an editor.

Who do you expect to make the changes your suggested?

**Tip for easy writing**:  Create text-expanders for common words you always want to use consistently, like _JavaScript_, or are that are hard to spell.  I currently use TextExpander, but I'm moving to Typinator.

**Comment by Tatsh** [comment]
I made the changes. I was incorrect in that `()` were optional for `alloc`. It actually seems that `alloc` is a special pointer defined by the runtime which points back to the class. But that doesn't mean you can avoid it. You still have to use it to call any initialiser:

```
>> ObjC.import('Foundation')
=> undefined
>> $.NSString.initWithFormat('%d', 1)
!! Error on line 1: TypeError: $.NSString.initWithFormat is not a function. (In '$.NSString.initWithFormat('%d', 1)', '$.NSString.initWithFormat' is undefined)
>> $.NSString.alloc.initWithFormat('%d', 1)
=> $("343")
>> $.NSString.__proto__
=> {"getProperty":[function anonymous], "setProperty":[function anonymous], "toString":[function anonymous], "isNil":[function anonymous]}
>> $.NSString.alloc.__proto__
=> $.NSString
```

I have had `osascript` segfault on me a few times upon doing these sorts of inspections.

```
 $ osascript -l JavaScript -i
>> ObjC.import('Foundation')
=> undefined
>> $.NSString.alloc
=> $.NSString
>> $.NSString.alloc.__proto__
=> {"getProperty":[function anonymous], "setProperty":[function anonymous], "toString":[function anonymous], "isNil":[function anonymou
s]}
>> $.NSString.alloc.initWithFormat()
!! Error on line 1: Error: wrong number of arguments for selector: initWithFormat:
>> $.NSString.alloc.initWithFormat('%d', 1)
Segmentation fault: 11
```

**Comment by sancarn** [comment]
As far as I understood, and this could be completely wrong, it's somewhat similar to VB6 where brackets imply a value is returned. No brackets imply that something is changed internally but no value is returned.

**Comment by Artoria2e5** [comment]
The example at [jxa-lib](https://github.com/Tatsh/jxa-lib/blob/ced78f005558239c229664d0433091e443418887/README.md#example-with-c-functions) seems to point out that `void*` is treated as `uint8_t*` by JXA. In other words, the `malloc` example is only taking the last little-endian byte of the result. You are only getting `whateverValue & 255` here.

Since there does not really seem to be a way to interpret pointers otherwise (`Ref` only does bytes) I guess we will be stuck with having to do a good old `foo[0] | foo[1] << 8 ...` for the actual value.
